pkg/cache/cache.go
Problem:
In a cluster with a large number of a single object, say 10k large
secrets, when the controller starts it attempts to list all of those
secrets and hits the client timeout
Solution:
Just increasing the client timeout does not work as the API server also
has a timeout. The API server ignores the limit when resourceVersion is
set to 0 which causes the call to take longer than either timeout
(running curl against the API server the call was taking over 3min on
average and pulling approx 2GB of data) so if resourceVersion is set to
0 reset it to empty string
=> Drop resourceVersion on lists when set to 0

pkg/controller/controller.go
Problem:
EnqueueKey rate limits the key and is called by sharedcontroller's RegisterHandler.
This is an issue because on startup we start enqueuing each key for each handler, causing the rate limit duration spike to hours very quickly.
Solution:
Adding the key to workqueue directly in EnqueueKey. Also what we used to do it 2.4.x,
https://github.com/rancher/norman/blob/release/v2.4/controller/generic_controller.go#L187
=> don't rate limit key when registering handlers

go.mod, pkg/controller/controller.go, pkg/workqueue/workqueue.go
Problem:
The bucket being used `rate.Limiter` does not have a maximum timeout so on startup if we process thousands of objects for the same item type this bucket can end up at hours long wait times. It then takes that same amount of time for the bucket to go back to zero. 
Solution:
Wrap the `rate.Limiter` with a max timeout of 2 min
=> Add a max timeout bucket

pkg/dynamic/gvks.go
Replaced CRD API from `v1beta1` to `v1` to support k8s v1.22.
Note that apiextensions.k8s.io/v1 for CRD is supported from k8s v1.16 making it OK to do straight change as Rancher v2.6 release to support k8s 1.18+.
=> Updated to use v1 API for CustomResourceDefinition

pkg/dynamic/controller.go
Previously, the dynamic informers returned from GetCache were not stored or
started if a dynamic cache was created. Now, getWatcherForGVK is used, which
will store the watcher to be used in subsequent calls to GetCache and start the
informer when necessary.
=> Use getWatcherForGVK in public GetCache method

pkg/controller/controller.go, pkg/controller/sharedcontroller.go
1. Rancher will start a usermanager controller for each downstream cluster, and will start management controller factory [here](https://github.com/rancher/rancher/blob/08ad9f793a2345478a26a514fca021c8e648f2f3/pkg/types/config/context.go#L476). The management controller factory will start only once cause it checked `started` state [here](https://github.com/rancher/lasso/blob/release/v2.5.8-patch1/pkg/controller/controller.go#L143). If there's something wrong with downstream cluster and usermanager controller has to stop, it canceled the context and skip goroutine [here](https://github.com/rancher/lasso/blob/release/v2.5.8-patch1/pkg/controller/sharedcontroller.go#L101). The management controller factory is never canceled, so that each time we start a usermanager controller, the goroutine …
=> [2.5] fix gouroutine leak when sharedcontroller has been started

pkg/controller/controller.go, pkg/controller/sharedcontrollerfactory.go
**Issue:**
https://github.com/rancher/rancher/issues/37350
**Original PR:**
https://github.com/rancher/lasso/pull/27
=> [Forwardport] v2.6: Only update change

pkg/dynamic/controller.go
By canceling the timeoutCtx here it has the side effect that any
cache later in the toWait list will be canceled if it hasn't finished
yet.  The side effect of this is that we only really wait for the
first cache and then if any other cache isn't don't we cancel them.
This is the source of errors like
failed to sync schemas: failed to sync cache for /v1, Kind=Secret
You may see these errors in the Rancher cluster agent when Steve is
starting, but you will definitely see these errors when running wtfk8s.
Signed-off-by: Darren Shepherd <darren@acorn.io>
=> Don't cancel timeout context after failure and first loop

pkg/controller/controller.go
I found it a bit tricky to understand how default work queue rate limiting works, and thought that it could be beneficial to recap the expected behavior for the next ones looking into it.
Graph:
X axis: number of failures
Y axis: time to wait in milliseconds
=> Explain default rate limiting behavior

pkg/cache/sql/informer/listoption_indexer.go, pkg/cache/sql/informer/listoption_indexer_test.go
Integration tests revealed this case result in error 500 because an incorrect query is produced in this case (`WHERE ()`).
This adds a test and addresses the case.
=> sql: listoption_indexer: handle the case with one empty filter correctly

pkg/cache/sql/db/client.go, pkg/cache/sql/db/client_test.go, pkg/cache/sql/informer/factory/db_mocks_test.go, pkg/cache/sql/informer/factory/factory_mocks_test.go, pkg/cache/sql/informer/indexer.go, pkg/cache/sql/informer/informer.go, pkg/cache/sql/informer/informer_mocks_test.go, pkg/cache/sql/informer/informer_test.go, pkg/cache/sql/informer/listoption_indexer.go, pkg/cache/sql/informer/listoption_indexer_test.go, pkg/cache/sql/informer/sql_mocks_test.go, pkg/cache/sql/informer/store_mocks_test.go, pkg/cache/sql/store/store.go, pkg/cache/sql/store/store_mocks_test.go
*Problem*: ListByOptions is currently unable to return the total object count (it will only return the requested page), and Steve needs it for the UI.
This PR adds the lasso bits, the accompanying Steve PR https://github.com/rancher/steve/pull/236 adds the Steve specific bits.
FWIW I have also run the integration tests and they are all green https://github.com/rancher/rancher/pull/46015
**Best reviewed commit-by-commit.**
**Please note this contains commits from https://github.com/rancher/lasso/pull/83, disregard the first two commits.**
**Please note this PR should be merged before https://github.com/rancher/steve/pull/236.**
=> sql: teach ListByOptions to return the total object count

pkg/cache/sql/informer/listoption_indexer.go
Because it was expanding the slice for a variadic function the first value in the params was being used for the %v and the remainder of the slice was treated as EXTRA see https://pkg.go.dev/fmt#hdr-Format_errors.
```
2024/07/09 08:25:44 [DEBUG] ListOptionIndexer prepared statement: SELECT o.object, o.objectnonce, o.dek, o.deknonce FROM "management.cattle.io_v3_Project" o
JOIN db2."management.cattle.io_v3_Project_fields" f ON o.key = f.key
WHERE
(f."metadata.namespace" = ?) 
ORDER BY f."metadata.namespace" ASC, f."metadata.name" ASC  
LIMIT ?
2024/07/09 08:25:44 [DEBUG] Params: local%!!(MISSING)(EXTRA int=100001)
```
=> Fix Param logging output.

pkg/metrics/register.go
Allows exposing metrics via a custom registerer, instead of forcing the use of prometheus.DefaultRegisterer. Also allows initializing metrics outside of init() which is generally considered an anti-pattern.
The default behavior of calling` prometheus.DefaultRegisterer.MustRegister()` is retained, ref:
https://github.com/prometheus/client_golang/blob/fec6b222d9ac46f61b0194fd343d5a10bf1e1d09/prometheus/registry.go#L174-L178
I also had to add a function to avoid registering the kubernetes internal workqueue metrics, to prevent conflicts in k3s where kubernetes itself registers those in the same process:
https://github.com/rancher/lasso/blob/32d96874d344eeeed641df40bdd38c50ad0213e7/pkg/metrics/workqueue.go#L21-L22
=> Expose metrics registration function

pkg/cache/sql/informer/informer_test.go
SQLite based caching uses an `Informer` that unsafely sets the `Indexer` as the ability to set it is not present in client-go at the moment.
Long term, we look forward contribute a patch to client-go to make that configurable.
Until then, we are adding this canary test that will panic in case the indexer cannot be set.
=> Add test that will break if UnsafeSet breaks

pkg/cache/sql/informer/indexer.go, pkg/cache/sql/informer/listoption_indexer.go, pkg/cache/sql/store/store.go
This prevents SQL injections even if a user is using lasso standalone as a client library.
This PR is meant to conclude conversations started here:
- https://github.com/rancher/lasso/pull/65#discussion_r1622389185
- https://github.com/rancher/lasso/pull/65#discussion_r1611626853
General posture is:
- use parameters (`?`) wherever possible
- Two cases fall outside of this category: table names and column names. Using parameters for them is not possible because the query planner needs to know them in order to prepare the query (unlike parameter values)
- column names: we pick them from a list, they are not free parameters
- table names: are sanitized
To make the last point as easy to audit as possible, I deliberately took a very pedantic approach here - sanitizing right before formatting …
=> sql: rationalization of parameter sanitization

pkg/cache/sql/informer/factory/informer_factory.go, pkg/cache/sql/informer/factory/informer_factory_test.go, pkg/cache/sql/informer/informer.go, pkg/cache/sql/informer/informer_test.go
Related to one of the tasks from rancher/rancher#45635. Adds the option for a `TransformFunc` which will be can be passed in when the Cache is created.
=> Adding support for transform functions

pkg/cache/sql/db/client.go, pkg/cache/sql/db/client_test.go, pkg/cache/sql/db/db_mocks_test.go, pkg/cache/sql/informer/factory/factory_mocks_test.go, pkg/cache/sql/informer/indexer.go, pkg/cache/sql/informer/indexer_test.go, pkg/cache/sql/informer/informer_test.go, pkg/cache/sql/informer/listoption_indexer.go, pkg/cache/sql/informer/listoption_indexer_test.go, pkg/cache/sql/informer/sql_mocks_test.go, pkg/cache/sql/informer/store_mocks_test.go, pkg/cache/sql/store/store.go, pkg/cache/sql/store/store_mocks_test.go, pkg/cache/sql/store/store_test.go
This 
- sets PRAGMAs correctly, before they were ignored as they used a wrong syntax
- removes the `shared=cache` option as https://github.com/rancher/lasso/pull/97 removed the need for it
- removes the mechanism retrying on SQLITE_BUSY, which is then unnecessary
- adds code to issue `BEGIN` on read-only transactions and `BEGIN IMMEDIATE` for transactions expected to write
The last point is necessary in order to avoid `SQLITE_BUSY` (5) errors in presence of multiple concurrent writing transactions. Without it `busy_timeout` would not be sufficient, see discussion below.
_best reviewed commit-by-commit_
Results from a quick and rough benchmark on my dev environment look good - performance is on par or superior compared to the situation without this PR.
This test lists the first page of …
=> sql: use WAL mode and set pragmas correctly

pkg/cache/sql/db/client.go
This is to remove options that only make sense when in-memory SQLite was an option.
=> sql: remove obsolete options

pkg/cache/sql/db/client.go, pkg/cache/sql/db/client_test.go
This ensures that the permissions on the file that SQLite is using are correct (0600) i.e. user read/write.
Part of https://github.com/rancher/rancher/issues/47825
=> Fix the file permissions on the sqlite db.

pkg/cache/sql/informer/factory/informer_factory.go, pkg/cache/sql/informer/factory/informer_factory_test.go, pkg/cache/sql/integration_test.go
Listable-but-unwatchable resources such as `nodes metrics.k8s.io/v1beta1` allow an Informer to be started, but it will by default log all watch failures.
Add a boolean flag to silence those errors.
partially addresses https://github.com/rancher/rancher/issues/46030
supports https://github.com/rancher/steve/pull/284
_best reviewed commit-by-commit_
=> sql: silence informer errors on unwatchable resources

pkg/cache/sql/store/store.go
client-go unfortunately "swallows" them
Partly addresses https://github.com/rancher/rancher/issues/48384
=> vai: log errors on add

pkg/cache/sql/informer/listoption_indexer.go, pkg/cache/sql/informer/listoption_indexer_test.go, pkg/cache/sql/informer/listoptions.go
This allows collection URLs to have a sort query that sorts on more than two fields
The use of `PrimaryField` and `SecondaryField` is too limiting, and leads to unlikely edge-cases,
like having a Secondary Field but no Primary Field. Better to just maintain parallel arrays of 
fields and sort-orders.
Related to [#48092](https://github.com/rancher/rancher/issues/48092)
=> Replace primary/secondary sort fields with an array of sort directives.

.github/renovate.json, .github/workflows/release.yaml, README.md, VERSION.md
https://github.com/rancher/rancher/issues/46901
=> [release/v0.1] Implement versioning ADR

pkg/dynamic/gvks.go
https://github.com/rancher/rancher/issues/49299
Allow for partial GVK discovery and report errors via logs.
Note: The `APIService` startup is a bit bumpier. Since the discovery is allowed to succeed before the imperative-api is up an running, it can take more time before the `APIService` is able to discover the new resources and allow users to access those resource via ther kube apiserver.
=> [main] Allow for partial discovery list

pkg/controller/controller.go, pkg/controller/sharedcontroller.go, pkg/controller/sharedcontrollerfactory.go, pkg/controller/sharedhandler.go, pkg/dynamic/controller.go, pkg/metrics/metrics.go
Similarly to how it was added to `lasso_controller_total_cached_object` in #95, having this label will allow us to differentiate handler executions from different contexts while analyzing Prometheus metrics. It reuses the same instrumentation added for identifying the caches: https://github.com/rancher/rancher/pull/46784.
This change should be backwards compatible with existing dashboards, as they must be already using `sum` in some way.
Some example queries using a local build:
- Top 10 downstream handler executions:
- Comparing handlers from 2 downstream with 3 nodes vs. 1 node respectively:
=> Add "ctx" label to lasso handler metrics

pkg/client/client.go, pkg/client/client_test.go
According to `apimachinery`'s [`Watch` interface](https://github.com/kubernetes/apimachinery/blob/master/pkg/watch/watch.go#L29-L51) (emphasis mine):
>  	// ResultChan returns a channel which will receive events from the event
>  	// producer. If an error occurs or Stop() is called, **the producer must
>  	// close this channel and release any resources used by the watch**.
>  	// Closing the result channel tells the consumer that no more events will be
>  	// sent.
>  	ResultChan() <-chan Event
However, our implementation of this interface does not satisfy that (I added a failing test that confirms it), forcing users to drain `ResultChan` after calling `Stop` in order to prevent memory leaks.
This change should not have any side effects on existing code with the mentioned workaround …
=> Watcher's ResultChan must be properly closed after Stop is called
